[package]
name = "rnb"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
indexmap = { version = "2", features = ["serde"] }
regex = "1"
parquet = {version = "54.3.1", features = ["arrow"]}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wide = "0.7.32"